<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Suraj-9693" ignored="0" name="Test" tests="8" failures="1" timestamp="13 Apr 2018 10:24:05 GMT" time="193.893" errors="0">
  <testcase name="ATest" time="6.005" classname="com.qa.TestScripts.Test1"/>
  <testcase name="afterTest" time="0.0" classname="com.qa.TestScripts.DataDrivenTest">
    <failure type="java.lang.AssertionError" message="Test is not Executed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test is not Executed expected [true] but found [false]
at com.qa.TestScripts.DataDrivenTest.afterTest(DataDrivenTest.java:35)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- afterTest -->
  <testcase name="excelTest" time="3.578" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.175" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.22" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.236" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.121" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.199" classname="com.qa.TestScripts.DataDrivenTest"/>
</testsuite> <!-- Test -->
